pipeline:
  docker:
    image: plugins/docker
    repo: toroid/mella
    tags:
      - latest

  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-mella
    tags: latest
    when:
      event: push
      status: success
      branch: master
